# Generated by Django 3.1.6 on 2021-02-14 10:04

import GinderApp.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('subscription', models.CharField(choices=[('default', 'Default'), ('silver', 'Silver'), ('gold', 'Gold')], default='default', max_length=150)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('viewed', models.ManyToManyField(blank=True, related_name='viewed_by', to='GinderApp.Profile')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=GinderApp.models.upload_post_image)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=GinderApp.models.upload_message_image)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='GinderApp.matchchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='GinderApp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='matchchat',
            name='user_profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to='GinderApp.profile'),
        ),
        migrations.AddField(
            model_name='matchchat',
            name='user_profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches2', to='GinderApp.profile'),
        ),
    ]
