# Generated by Django 3.1.6 on 2021-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchchat',
            options={'verbose_name': 'MatchChat', 'verbose_name_plural': 'MatchChats'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='GinderApp.Post'),
        ),
    ]
