# Generated by Django 3.1.6 on 2021-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinderApp', '0002_auto_20210216_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='GinderApp.Profile'),
        ),
    ]
