# Generated by Django 3.1.6 on 2021-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinderApp', '0004_auto_20210213_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked',
            field=models.ManyToManyField(related_name='seen', to='GinderApp.Profile'),
        ),
    ]
