# Generated by Django 3.1.6 on 2021-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinderApp', '0005_profile_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='checked',
            field=models.ManyToManyField(related_name='seen_by', to='GinderApp.Profile'),
        ),
    ]
