# Generated by Django 3.1.6 on 2021-02-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinderApp', '0006_auto_20210213_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='checked',
        ),
        migrations.AddField(
            model_name='profile',
            name='viewed',
            field=models.ManyToManyField(related_name='viewed_by', to='GinderApp.Profile'),
        ),
    ]
