# Generated by Django 3.1.6 on 2021-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinderApp', '0007_auto_20210213_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='GinderApp.Profile'),
        ),
    ]
