# Generated by Django 3.1.6 on 2021-02-14 09:33

import GinderApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GinderApp', '0008_auto_20210214_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to='GinderApp.profile')),
                ('user_profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches2', to='GinderApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=GinderApp.models.upload_message_image)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='GinderApp.match_chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='GinderApp.profile')),
            ],
        ),
    ]
